# Generated by Django 4.2.7 on 2025-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=150)),
                ('sub_type', models.CharField(choices=[('CODING', 'Coding'), ('THEORY', 'Theory')], max_length=20)),
                ('sub_img', models.ImageField(upload_to='images/')),
                ('num_units', models.ImageField(upload_to='')),
            ],
        ),
    ]
