# Generated by Django 4.2.7 on 2025-02-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=250)),
                ('unit_file', models.FileField(upload_to='unit_files/')),
                ('unit_number', models.IntegerField()),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.subject')),
            ],
        ),
    ]
