# Generated by Django 4.2.7 on 2025-02-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_subject_sub_name_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='num_units',
            field=models.IntegerField(),
        ),
    ]
