# Generated by Django 4.2.7 on 2025-02-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_subject_num_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='units',
            options={'verbose_name_plural': 'Units'},
        ),
        migrations.CreateModel(
            name='ImpQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_file', models.FileField(upload_to='imp_questions/')),
                ('subject_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.subject')),
            ],
        ),
    ]
